language: go
go:
- 1.x
sudo: false
before_script:
  - sudo curl -sfSL https://github.com/haproxytech/dataplaneapi/releases/download/v2.1.0/dataplaneapi_2.1.0_Linux_x86_64.tar.gz -o dataplane.tar.gz
  - sudo mkdir /tmp/dataplane
  - sudo tar -xzf dataplane.tar.gz -C /tmp/dataplane --strip-components=1
  - sudo mv /tmp/dataplane/dataplaneapi /usr/local/bin/dataplaneapi
  - sudo chmod +x /usr/local/bin/dataplaneapi
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:vbernat/haproxy-2.1
  - sudo apt-get update
  - sudo apt-get install -y haproxy=2.1.\*
  - haproxy -vv
script: make travis
addons:
  apt:
    update: true
    packages:
      - libssl-dev
      - zlib1g-dev
      - libpcre3-dev
